### ISSUE TITLE
Missing implementation

### ISSUE THREAD

**Issue by databoy** [MakeSchool-Tutorials/Doodler-Cpp#1]
Great tute! Starts strong, but spends a lot of time before getting to the actual multipeer networking that should be the heart of the material. 

Unfortunately, the precedent started by showing the finished result seems to have disappeared. It starts with the color picker being left out. Then the entire networking controls are only revealed piecemeal.

I think linking to the source code of the finished product would be helpful. Thanks!

**Comment by danielhaaser** [comment]
Thanks!  That's good feedback.  Here's the finished source code:
https://github.com/MakeSchool/Doodler-Cpp

**Comment by databoy** [comment]
I appreciate the quick response! It was very helpful, indeed! 

I found only one thing, I think. The last line of packLineData function,

```
return std::string(buffer.GetString(), buffer.Size());
```

would only compile with the latest Cocos2D (3.9) if changed to: 

```
return std::string(buffer.GetString(), buffer.GetSize());
```

But that may not be optimal, as I didn't search for a solution (just looked at the headers and changed the call).
